In [1]:
from __future__ import division
import pandas as pd
import numpy as np
import re
from mpl_toolkits.basemap import pyproj

In [2]:
def qc(cell):
    match = re.search(r'^\[\[[-\d,\.\[\]]+\]\]$', cell)
    if match:
        return np.asarray(eval(cell))
    else:
        return np.nan

In [3]:
sproj = '+proj=tmerc +lat_0=41.06 +lon_0=-8.765127 +x_0=0 +y_0=0 +k_0=1 +lat_ts=41 +ellps=GRS80 +units=m +no_defs'
proj = pyproj.Proj(sproj)

In [34]:
floc = '/Users/Bronco/Classes/General_assembly/DAT_SF_13_homework/Final_project/kaggle/taxi_trajectory_prediction/train.csv'
taxi_data = pd.read_csv(floc, chunksize=1000)
chunk = taxi_data.read(100000)

In [35]:
chunk

,TRIP_ID,CALL_TYPE,ORIGIN_CALL,ORIGIN_STAND,TAXI_ID,TIMESTAMP,DAY_TYPE,MISSING_DATA,POLYLINE
0,1372636858620000589,C,NaN,NaN,20000589,1372636858,A,False,"[[-8.618643,41.141412],[-8.618499,41.141376],[..."
1,1372637303620000596,B,NaN,7,20000596,1372637303,A,False,"[[-8.639847,41.159826],[-8.640351,41.159871],[..."
2,1372636951620000320,C,NaN,NaN,20000320,1372636951,A,False,"[[-8.612964,41.140359],[-8.613378,41.14035],[-..."
3,1372636854620000520,C,NaN,NaN,20000520,1372636854,A,False,"[[-8.574678,41.151951],[-8.574705,41.151942],[..."
4,1372637091620000337,C,NaN,NaN,20000337,1372637091,A,False,"[[-8.645994,41.18049],[-8.645949,41.180517],[-..."
5,1372636965620000231,C,NaN,NaN,20000231,1372636965,A,False,"[[-8.615502,41.140674],[-8.614854,41.140926],[..."
6,1372637210620000456,C,NaN,NaN,20000456,1372637210,A,False,"[[-8.57952,41.145948],[-8.580942,41.145039],[-..."
7,1372637299620000011,C,NaN,NaN,20000011,1372637299,A,False,"[[-8.617563,41.146182],[-8.617527,41.145849],[..."
8,1372637274620000403,C,NaN,NaN,20000403,1372637274,A,False,"[[-8.611794,41.140557],[-8.611785,41.140575],[..."
9,1372637905620000320,C,NaN,NaN,20000320,1372637905,A,False,"[[-8.615907,41.140557],[-8.614449,41.141088],[..."
10,1372636875620000233,C,NaN,NaN,20000233,1372636875,A,False,"[[-8.619894,41.148009],[-8.620164,41.14773],[-..."
11,1372637984620000520,C,NaN,NaN,20000520,1372637984,A,False,"[[-8.56242,41.168403],[-8.562429,41.168358],[-..."
12,1372637343620000571,A,31508,NaN,20000571,1372637343,A,False,"[[-8.618868,41.155101],[-8.6175,41.154912],[-8..."
13,1372638595620000233,C,NaN,NaN,20000233,1372638595,A,False,"[[-8.608716,41.153499],[-8.607627,41.153481],[..."
14,1372638151620000231,C,NaN,NaN,20000231,1372638151,A,False,"[[-8.612208,41.14053],[-8.612235,41.140521],[-..."
15,1372637610620000497,B,NaN,13,20000497,1372637610,A,False,"[[-8.585145,41.164857],[-8.584146,41.164704],[..."
16,1372638481620000403,B,NaN,28,20000403,1372638481,A,False,"[[-8.584263,41.163156],[-8.584695,41.163003],[..."
17,1372639135620000570,A,33180,NaN,20000570,1372639135,A,False,"[[-8.666757,41.174055],[-8.666784,41.174064],[..."
18,1372637482620000005,C,NaN,NaN,20000005,1372637482,A,False,"[[-8.599239,41.149188],[-8.598681,41.149296],[..."
19,1372639181620000089,C,NaN,NaN,20000089,1372639181,A,False,"[[-8.643807,41.168979],[-8.642529,41.170113],[..."
20,1372638161620000423,C,NaN,NaN,20000423,1372638161,A,False,"[[-8.609706,41.151303],[-8.609562,41.151474],[..."
21,1372637254620000657,A,39233,NaN,20000657,1372637254,A,False,"[[-8.660646,41.168574],[-8.661087,41.167926],[..."
22,1372638502620000320,C,NaN,NaN,20000320,1372638502,A,False,"[[-8.612955,41.140377],[-8.612991,41.140359],[..."
23,1372639960620000309,B,NaN,38,20000309,1372639960,A,False,"[[-8.60418,41.160969],[-8.603874,41.1615],[-8...."
24,1372637658620000596,A,22864,NaN,20000596,1372637658,A,False,"[[-8.665686,41.170626],[-8.665677,41.170653],[..."
25,1372639092620000233,C,NaN,NaN,20000233,1372639092,A,False,"[[-8.632737,41.168295],[-8.6328,41.16825],[-8...."
26,1372639535620000161,A,25862,NaN,20000161,1372639535,A,False,"[[-8.648226,41.148333],[-8.648514,41.148297],[..."
27,1372640499620000596,C,NaN,NaN,20000596,1372640499,A,False,"[[-8.638227,41.159592],[-8.637543,41.15925],[-..."
28,1372639635620000178,B,NaN,52,20000178,1372639635,A,False,"[[-8.613243,41.154444],[-8.612811,41.153733],[..."
29,1372640555620000235,C,NaN,NaN,20000235,1372640555,A,False,"[[-8.611065,41.149431],[-8.611209,41.149368],[..."
...,...,...,...,...,...,...,...,...,...
99970,1374432274620000017,A,12190,NaN,20000017,1374432274,A,False,"[[-8.566857,41.163363],[-8.566866,41.163372],[..."
99971,1374432386620000409,A,44045,NaN,20000409,1374432386,A,False,"[[-8.654931,41.155686],[-8.655624,41.155443],[..."
99972,1374434095620000482,B,NaN,7,20000482,1374434095,A,False,"[[-8.639838,41.159745],[-8.640459,41.159772],[..."
99973,1374381091620000161,C,NaN,NaN,20000161,1374381091,A,False,"[[-8.628885,41.161041],[-8.628786,41.160969],[..."
99974,1374433135620000640,C,NaN,NaN,20000640,1374433135,A,False,"[[-8.672607,41.149008],[-8.670933,41.148882],[..."
99975,1374431233620000520,B,NaN,15,20000520,1374431233,A,False,"[[-8.585685,41.148576],[-8.585694,41.148675],[..."
99976,1374428577620000697,A,33597,NaN,20000697,1374428577,A,False,"[[-8.678367,41.15304],[-8.679078,41.15385],[-8..."
99977,1374432928620000410,A,2002,NaN,20000410,1374432928,A,False,"[[-8.640729,41.160033],[-8.640828,41.16006],[-..."
99978,1374425122620000007,B,NaN,12,20000007,1374425122,A,False,"[[-8.630478,41.154804],[-8.630505,41.15475],[-..."
99979,1374433432620000574,A,2002,NaN,20000574,1374433432,A,False,"[[-8.647785,41.150799],[-8.647704,41.150754],[..."
99980,1374433957620000047,C,NaN,NaN,20000047,1374433957,A,False,"[[-8.613117,41.14341],[-8.613054,41.143446],[-..."
99981,1374433518620000623,A,2002,NaN,20000623,1374433518,A,False,"[[-8.619966,41.146812],[-8.619993,41.146812],[..."
99982,1374434466620000345,A,21842,NaN,20000345,1374434466,A,False,"[[-8.587962,41.147469],[-8.587827,41.147784],[..."
99983,1374434094620000557,B,NaN,23,20000557,1374434094,A,False,"[[-8.612586,41.145921],[-8.612199,41.146038],[..."
99984,1374432882620000352,C,NaN,NaN,20000352,1374432882,A,False,"[[-8.654265,41.180526],[-8.653977,41.179914],[..."
99985,1374433783620000686,B,NaN,27,20000686,1374433783,A,False,"[[-8.608698,41.147874],[-8.608554,41.14773],[-..."
99986,1374434268620000341,A,6654,NaN,20000341,1374434268,A,False,"[[-8.607303,41.14566],[-8.607069,41.145885],[-..."
99987,1374431063620000419,C,NaN,NaN,20000419,1374431063,A,False,"[[-8.610822,41.145615],[-8.610849,41.14566],[-..."
99988,1374432016620000658,B,NaN,57,20000658,1374432016,A,False,"[[-8.610903,41.145579],[-8.610948,41.14566],[-..."
99989,1374434617620000146,B,NaN,34,20000146,1374434617,A,False,"[[-8.615538,41.14071],[-8.61552,41.140692],[-8..."
99990,1374433008620000250,B,NaN,9,20000250,1374433008,A,False,"[[-8.60652,41.144589],[-8.60697,41.144742],[-8..."
99991,1374432749620000023,A,59871,NaN,20000023,1374432749,A,False,"[[-8.688888,41.174406],[-8.689023,41.175819],[..."
99992,1374434381620000618,A,2002,NaN,20000618,1374434381,A,False,"[[-8.574732,41.14269],[-8.574723,41.142663],[-..."
99993,1374431340620000384,B,NaN,10,20000384,1374431340,A,False,"[[-8.607105,41.150277],[-8.607105,41.150268],[..."
99994,1374431335620000271,A,41673,NaN,20000271,1374431335,A,False,"[[-8.613252,41.147901],[-8.61309,41.148306],[-..."
99995,1374433338620000398,B,NaN,36,20000398,1374433338,A,False,"[[-8.649297,41.154309],[-8.650044,41.154228],[..."
99996,1374433379620000506,B,NaN,53,20000506,1374433379,A,False,"[[-8.6139,41.141133],[-8.613891,41.141115],[-8..."
99997,1374433756620000435,B,NaN,9,20000435,1374433756,A,False,"[[-8.606475,41.144508],[-8.60652,41.144517],[-..."
99998,1374434789620000074,A,60678,NaN,20000074,1374434789,A,False,"[[-8.604945,41.149692],[-8.605368,41.149773],[..."
99999,1374432807620000174,B,NaN,10,20000174,1374432807,A,False,"[[-8.606799,41.150997],[-8.606808,41.15097],[-..."

In [36]:
chunk.POLYLINE = chunk.POLYLINE.apply(qc)
chunk.dropna(axis='rows', subset=['POLYLINE'], inplace=True)
chunk

,TRIP_ID,CALL_TYPE,ORIGIN_CALL,ORIGIN_STAND,TAXI_ID,TIMESTAMP,DAY_TYPE,MISSING_DATA,POLYLINE
0,1372636858620000589,C,NaN,NaN,20000589,1372636858,A,False,"[[-8.618643, 41.141412], [-8.618499, 41.141376..."
1,1372637303620000596,B,NaN,7,20000596,1372637303,A,False,"[[-8.639847, 41.159826], [-8.640351, 41.159871..."
2,1372636951620000320,C,NaN,NaN,20000320,1372636951,A,False,"[[-8.612964, 41.140359], [-8.613378, 41.14035]..."
3,1372636854620000520,C,NaN,NaN,20000520,1372636854,A,False,"[[-8.574678, 41.151951], [-8.574705, 41.151942..."
4,1372637091620000337,C,NaN,NaN,20000337,1372637091,A,False,"[[-8.645994, 41.18049], [-8.645949, 41.180517]..."
5,1372636965620000231,C,NaN,NaN,20000231,1372636965,A,False,"[[-8.615502, 41.140674], [-8.614854, 41.140926..."
6,1372637210620000456,C,NaN,NaN,20000456,1372637210,A,False,"[[-8.57952, 41.145948], [-8.580942, 41.145039]..."
7,1372637299620000011,C,NaN,NaN,20000011,1372637299,A,False,"[[-8.617563, 41.146182], [-8.617527, 41.145849..."
8,1372637274620000403,C,NaN,NaN,20000403,1372637274,A,False,"[[-8.611794, 41.140557], [-8.611785, 41.140575..."
9,1372637905620000320,C,NaN,NaN,20000320,1372637905,A,False,"[[-8.615907, 41.140557], [-8.614449, 41.141088..."
10,1372636875620000233,C,NaN,NaN,20000233,1372636875,A,False,"[[-8.619894, 41.148009], [-8.620164, 41.14773]..."
11,1372637984620000520,C,NaN,NaN,20000520,1372637984,A,False,"[[-8.56242, 41.168403], [-8.562429, 41.168358]..."
12,1372637343620000571,A,31508,NaN,20000571,1372637343,A,False,"[[-8.618868, 41.155101], [-8.6175, 41.154912],..."
13,1372638595620000233,C,NaN,NaN,20000233,1372638595,A,False,"[[-8.608716, 41.153499], [-8.607627, 41.153481..."
14,1372638151620000231,C,NaN,NaN,20000231,1372638151,A,False,"[[-8.612208, 41.14053], [-8.612235, 41.140521]..."
15,1372637610620000497,B,NaN,13,20000497,1372637610,A,False,"[[-8.585145, 41.164857], [-8.584146, 41.164704..."
16,1372638481620000403,B,NaN,28,20000403,1372638481,A,False,"[[-8.584263, 41.163156], [-8.584695, 41.163003..."
17,1372639135620000570,A,33180,NaN,20000570,1372639135,A,False,"[[-8.666757, 41.174055], [-8.666784, 41.174064..."
18,1372637482620000005,C,NaN,NaN,20000005,1372637482,A,False,"[[-8.599239, 41.149188], [-8.598681, 41.149296..."
19,1372639181620000089,C,NaN,NaN,20000089,1372639181,A,False,"[[-8.643807, 41.168979], [-8.642529, 41.170113..."
20,1372638161620000423,C,NaN,NaN,20000423,1372638161,A,False,"[[-8.609706, 41.151303], [-8.609562, 41.151474..."
21,1372637254620000657,A,39233,NaN,20000657,1372637254,A,False,"[[-8.660646, 41.168574], [-8.661087, 41.167926..."
22,1372638502620000320,C,NaN,NaN,20000320,1372638502,A,False,"[[-8.612955, 41.140377], [-8.612991, 41.140359..."
23,1372639960620000309,B,NaN,38,20000309,1372639960,A,False,"[[-8.60418, 41.160969], [-8.603874, 41.1615], ..."
24,1372637658620000596,A,22864,NaN,20000596,1372637658,A,False,"[[-8.665686, 41.170626], [-8.665677, 41.170653..."
25,1372639092620000233,C,NaN,NaN,20000233,1372639092,A,False,"[[-8.632737, 41.168295], [-8.6328, 41.16825], ..."
26,1372639535620000161,A,25862,NaN,20000161,1372639535,A,False,"[[-8.648226, 41.148333], [-8.648514, 41.148297..."
27,1372640499620000596,C,NaN,NaN,20000596,1372640499,A,False,"[[-8.638227, 41.159592], [-8.637543, 41.15925]..."
28,1372639635620000178,B,NaN,52,20000178,1372639635,A,False,"[[-8.613243, 41.154444], [-8.612811, 41.153733..."
29,1372640555620000235,C,NaN,NaN,20000235,1372640555,A,False,"[[-8.611065, 41.149431], [-8.611209, 41.149368..."
...,...,...,...,...,...,...,...,...,...
99970,1374432274620000017,A,12190,NaN,20000017,1374432274,A,False,"[[-8.566857, 41.163363], [-8.566866, 41.163372..."
99971,1374432386620000409,A,44045,NaN,20000409,1374432386,A,False,"[[-8.654931, 41.155686], [-8.655624, 41.155443..."
99972,1374434095620000482,B,NaN,7,20000482,1374434095,A,False,"[[-8.639838, 41.159745], [-8.640459, 41.159772..."
99973,1374381091620000161,C,NaN,NaN,20000161,1374381091,A,False,"[[-8.628885, 41.161041], [-8.628786, 41.160969..."
99974,1374433135620000640,C,NaN,NaN,20000640,1374433135,A,False,"[[-8.672607, 41.149008], [-8.670933, 41.148882..."
99975,1374431233620000520,B,NaN,15,20000520,1374431233,A,False,"[[-8.585685, 41.148576], [-8.585694, 41.148675..."
99976,1374428577620000697,A,33597,NaN,20000697,1374428577,A,False,"[[-8.678367, 41.15304], [-8.679078, 41.15385],..."
99977,1374432928620000410,A,2002,NaN,20000410,1374432928,A,False,"[[-8.640729, 41.160033], [-8.640828, 41.16006]..."
99978,1374425122620000007,B,NaN,12,20000007,1374425122,A,False,"[[-8.630478, 41.154804], [-8.630505, 41.15475]..."
99979,1374433432620000574,A,2002,NaN,20000574,1374433432,A,False,"[[-8.647785, 41.150799], [-8.647704, 41.150754..."
99980,1374433957620000047,C,NaN,NaN,20000047,1374433957,A,False,"[[-8.613117, 41.14341], [-8.613054, 41.143446]..."
99981,1374433518620000623,A,2002,NaN,20000623,1374433518,A,False,"[[-8.619966, 41.146812], [-8.619993, 41.146812..."
99982,1374434466620000345,A,21842,NaN,20000345,1374434466,A,False,"[[-8.587962, 41.147469], [-8.587827, 41.147784..."
99983,1374434094620000557,B,NaN,23,20000557,1374434094,A,False,"[[-8.612586, 41.145921], [-8.612199, 41.146038..."
99984,1374432882620000352,C,NaN,NaN,20000352,1374432882,A,False,"[[-8.654265, 41.180526], [-8.653977, 41.179914..."
99985,1374433783620000686,B,NaN,27,20000686,1374433783,A,False,"[[-8.608698, 41.147874], [-8.608554, 41.14773]..."
99986,1374434268620000341,A,6654,NaN,20000341,1374434268,A,False,"[[-8.607303, 41.14566], [-8.607069, 41.145885]..."
99987,1374431063620000419,C,NaN,NaN,20000419,1374431063,A,False,"[[-8.610822, 41.145615], [-8.610849, 41.14566]..."
99988,1374432016620000658,B,NaN,57,20000658,1374432016,A,False,"[[-8.610903, 41.145579], [-8.610948, 41.14566]..."
99989,1374434617620000146,B,NaN,34,20000146,1374434617,A,False,"[[-8.615538, 41.14071], [-8.61552, 41.140692],..."
99990,1374433008620000250,B,NaN,9,20000250,1374433008,A,False,"[[-8.60652, 41.144589], [-8.60697, 41.144742],..."
99991,1374432749620000023,A,59871,NaN,20000023,1374432749,A,False,"[[-8.688888, 41.174406], [-8.689023, 41.175819..."
99992,1374434381620000618,A,2002,NaN,20000618,1374434381,A,False,"[[-8.574732, 41.14269], [-8.574723, 41.142663]..."
99993,1374431340620000384,B,NaN,10,20000384,1374431340,A,False,"[[-8.607105, 41.150277], [-8.607105, 41.150268..."
99994,1374431335620000271,A,41673,NaN,20000271,1374431335,A,False,"[[-8.613252, 41.147901], [-8.61309, 41.148306]..."
99995,1374433338620000398,B,NaN,36,20000398,1374433338,A,False,"[[-8.649297, 41.154309], [-8.650044, 41.154228..."
99996,1374433379620000506,B,NaN,53,20000506,1374433379,A,False,"[[-8.6139, 41.141133], [-8.613891, 41.141115],..."
99997,1374433756620000435,B,NaN,9,20000435,1374433756,A,False,"[[-8.606475, 41.144508], [-8.60652, 41.144517]..."
99998,1374434789620000074,A,60678,NaN,20000074,1374434789,A,False,"[[-8.604945, 41.149692], [-8.605368, 41.149773..."
99999,1374432807620000174,B,NaN,10,20000174,1374432807,A,False,"[[-8.606799, 41.150997], [-8.606808, 41.15097]..."

In [37]:
chunk.drop(['TRIP_ID', 'MISSING_DATA', 'ORIGIN_CALL','ORIGIN_STAND'], axis = 'columns', inplace=True)

In [38]:
chunk = pd.get_dummies(chunk, columns=['CALL_TYPE', 'DAY_TYPE'])
chunk

,TAXI_ID,TIMESTAMP,POLYLINE,CALL_TYPE_A,CALL_TYPE_B,CALL_TYPE_C,DAY_TYPE_A
0,20000589,1372636858,"[[-8.618643, 41.141412], [-8.618499, 41.141376...",0,0,1,1
1,20000596,1372637303,"[[-8.639847, 41.159826], [-8.640351, 41.159871...",0,1,0,1
2,20000320,1372636951,"[[-8.612964, 41.140359], [-8.613378, 41.14035]...",0,0,1,1
3,20000520,1372636854,"[[-8.574678, 41.151951], [-8.574705, 41.151942...",0,0,1,1
4,20000337,1372637091,"[[-8.645994, 41.18049], [-8.645949, 41.180517]...",0,0,1,1
5,20000231,1372636965,"[[-8.615502, 41.140674], [-8.614854, 41.140926...",0,0,1,1
6,20000456,1372637210,"[[-8.57952, 41.145948], [-8.580942, 41.145039]...",0,0,1,1
7,20000011,1372637299,"[[-8.617563, 41.146182], [-8.617527, 41.145849...",0,0,1,1
8,20000403,1372637274,"[[-8.611794, 41.140557], [-8.611785, 41.140575...",0,0,1,1
9,20000320,1372637905,"[[-8.615907, 41.140557], [-8.614449, 41.141088...",0,0,1,1
10,20000233,1372636875,"[[-8.619894, 41.148009], [-8.620164, 41.14773]...",0,0,1,1
11,20000520,1372637984,"[[-8.56242, 41.168403], [-8.562429, 41.168358]...",0,0,1,1
12,20000571,1372637343,"[[-8.618868, 41.155101], [-8.6175, 41.154912],...",1,0,0,1
13,20000233,1372638595,"[[-8.608716, 41.153499], [-8.607627, 41.153481...",0,0,1,1
14,20000231,1372638151,"[[-8.612208, 41.14053], [-8.612235, 41.140521]...",0,0,1,1
15,20000497,1372637610,"[[-8.585145, 41.164857], [-8.584146, 41.164704...",0,1,0,1
16,20000403,1372638481,"[[-8.584263, 41.163156], [-8.584695, 41.163003...",0,1,0,1
17,20000570,1372639135,"[[-8.666757, 41.174055], [-8.666784, 41.174064...",1,0,0,1
18,20000005,1372637482,"[[-8.599239, 41.149188], [-8.598681, 41.149296...",0,0,1,1
19,20000089,1372639181,"[[-8.643807, 41.168979], [-8.642529, 41.170113...",0,0,1,1
20,20000423,1372638161,"[[-8.609706, 41.151303], [-8.609562, 41.151474...",0,0,1,1
21,20000657,1372637254,"[[-8.660646, 41.168574], [-8.661087, 41.167926...",1,0,0,1
22,20000320,1372638502,"[[-8.612955, 41.140377], [-8.612991, 41.140359...",0,0,1,1
23,20000309,1372639960,"[[-8.60418, 41.160969], [-8.603874, 41.1615], ...",0,1,0,1
24,20000596,1372637658,"[[-8.665686, 41.170626], [-8.665677, 41.170653...",1,0,0,1
25,20000233,1372639092,"[[-8.632737, 41.168295], [-8.6328, 41.16825], ...",0,0,1,1
26,20000161,1372639535,"[[-8.648226, 41.148333], [-8.648514, 41.148297...",1,0,0,1
27,20000596,1372640499,"[[-8.638227, 41.159592], [-8.637543, 41.15925]...",0,0,1,1
28,20000178,1372639635,"[[-8.613243, 41.154444], [-8.612811, 41.153733...",0,1,0,1
29,20000235,1372640555,"[[-8.611065, 41.149431], [-8.611209, 41.149368...",0,0,1,1
...,...,...,...,...,...,...,...
99970,20000017,1374432274,"[[-8.566857, 41.163363], [-8.566866, 41.163372...",1,0,0,1
99971,20000409,1374432386,"[[-8.654931, 41.155686], [-8.655624, 41.155443...",1,0,0,1
99972,20000482,1374434095,"[[-8.639838, 41.159745], [-8.640459, 41.159772...",0,1,0,1
99973,20000161,1374381091,"[[-8.628885, 41.161041], [-8.628786, 41.160969...",0,0,1,1
99974,20000640,1374433135,"[[-8.672607, 41.149008], [-8.670933, 41.148882...",0,0,1,1
99975,20000520,1374431233,"[[-8.585685, 41.148576], [-8.585694, 41.148675...",0,1,0,1
99976,20000697,1374428577,"[[-8.678367, 41.15304], [-8.679078, 41.15385],...",1,0,0,1
99977,20000410,1374432928,"[[-8.640729, 41.160033], [-8.640828, 41.16006]...",1,0,0,1
99978,20000007,1374425122,"[[-8.630478, 41.154804], [-8.630505, 41.15475]...",0,1,0,1
99979,20000574,1374433432,"[[-8.647785, 41.150799], [-8.647704, 41.150754...",1,0,0,1
99980,20000047,1374433957,"[[-8.613117, 41.14341], [-8.613054, 41.143446]...",0,0,1,1
99981,20000623,1374433518,"[[-8.619966, 41.146812], [-8.619993, 41.146812...",1,0,0,1
99982,20000345,1374434466,"[[-8.587962, 41.147469], [-8.587827, 41.147784...",1,0,0,1
99983,20000557,1374434094,"[[-8.612586, 41.145921], [-8.612199, 41.146038...",0,1,0,1
99984,20000352,1374432882,"[[-8.654265, 41.180526], [-8.653977, 41.179914...",0,0,1,1
99985,20000686,1374433783,"[[-8.608698, 41.147874], [-8.608554, 41.14773]...",0,1,0,1
99986,20000341,1374434268,"[[-8.607303, 41.14566], [-8.607069, 41.145885]...",1,0,0,1
99987,20000419,1374431063,"[[-8.610822, 41.145615], [-8.610849, 41.14566]...",0,0,1,1
99988,20000658,1374432016,"[[-8.610903, 41.145579], [-8.610948, 41.14566]...",0,1,0,1
99989,20000146,1374434617,"[[-8.615538, 41.14071], [-8.61552, 41.140692],...",0,1,0,1
99990,20000250,1374433008,"[[-8.60652, 41.144589], [-8.60697, 41.144742],...",0,1,0,1
99991,20000023,1374432749,"[[-8.688888, 41.174406], [-8.689023, 41.175819...",1,0,0,1
99992,20000618,1374434381,"[[-8.574732, 41.14269], [-8.574723, 41.142663]...",1,0,0,1
99993,20000384,1374431340,"[[-8.607105, 41.150277], [-8.607105, 41.150268...",0,1,0,1
99994,20000271,1374431335,"[[-8.613252, 41.147901], [-8.61309, 41.148306]...",1,0,0,1
99995,20000398,1374433338,"[[-8.649297, 41.154309], [-8.650044, 41.154228...",0,1,0,1
99996,20000506,1374433379,"[[-8.6139, 41.141133], [-8.613891, 41.141115],...",0,1,0,1
99997,20000435,1374433756,"[[-8.606475, 41.144508], [-8.60652, 41.144517]...",0,1,0,1
99998,20000074,1374434789,"[[-8.604945, 41.149692], [-8.605368, 41.149773...",1,0,0,1
99999,20000174,1374432807,"[[-8.606799, 41.150997], [-8.606808, 41.15097]...",0,1,0,1

In [39]:
chunk['Y'] = chunk.POLYLINE.apply(lambda x: x[-1])
chunk

,TAXI_ID,TIMESTAMP,POLYLINE,CALL_TYPE_A,CALL_TYPE_B,CALL_TYPE_C,DAY_TYPE_A,Y
0,20000589,1372636858,"[[-8.618643, 41.141412], [-8.618499, 41.141376...",0,0,1,1,"[-8.630838, 41.154489]"
1,20000596,1372637303,"[[-8.639847, 41.159826], [-8.640351, 41.159871...",0,1,0,1,"[-8.66574, 41.170671]"
2,20000320,1372636951,"[[-8.612964, 41.140359], [-8.613378, 41.14035]...",0,0,1,1,"[-8.61597, 41.14053]"
3,20000520,1372636854,"[[-8.574678, 41.151951], [-8.574705, 41.151942...",0,0,1,1,"[-8.607996, 41.142915]"
4,20000337,1372637091,"[[-8.645994, 41.18049], [-8.645949, 41.180517]...",0,0,1,1,"[-8.687268, 41.178087]"
5,20000231,1372636965,"[[-8.615502, 41.140674], [-8.614854, 41.140926...",0,0,1,1,"[-8.578224, 41.160717]"
6,20000456,1372637210,"[[-8.57952, 41.145948], [-8.580942, 41.145039]...",0,0,1,1,"[-8.603973, 41.142816]"
7,20000011,1372637299,"[[-8.617563, 41.146182], [-8.617527, 41.145849...",0,0,1,1,"[-8.6247, 41.161554]"
8,20000403,1372637274,"[[-8.611794, 41.140557], [-8.611785, 41.140575...",0,0,1,1,"[-8.589402, 41.163309]"
9,20000320,1372637905,"[[-8.615907, 41.140557], [-8.614449, 41.141088...",0,0,1,1,"[-8.604594, 41.134158]"
10,20000233,1372636875,"[[-8.619894, 41.148009], [-8.620164, 41.14773]...",0,0,1,1,"[-8.60949, 41.157351]"
11,20000520,1372637984,"[[-8.56242, 41.168403], [-8.562429, 41.168358]...",0,0,1,1,"[-8.623017, 41.164218]"
12,20000571,1372637343,"[[-8.618868, 41.155101], [-8.6175, 41.154912],...",1,0,0,1,"[-8.575065, 41.162265]"
13,20000233,1372638595,"[[-8.608716, 41.153499], [-8.607627, 41.153481...",0,0,1,1,"[-8.632737, 41.168295]"
14,20000231,1372638151,"[[-8.612208, 41.14053], [-8.612235, 41.140521]...",0,0,1,1,"[-8.606772, 41.15826]"
15,20000497,1372637610,"[[-8.585145, 41.164857], [-8.584146, 41.164704...",0,1,0,1,"[-8.628147, 41.157522]"
16,20000403,1372638481,"[[-8.584263, 41.163156], [-8.584695, 41.163003...",0,1,0,1,"[-8.641566, 41.142672]"
17,20000570,1372639135,"[[-8.666757, 41.174055], [-8.666784, 41.174064...",1,0,0,1,"[-8.662554, 41.181714]"
18,20000005,1372637482,"[[-8.599239, 41.149188], [-8.598681, 41.149296...",0,0,1,1,"[-8.584326, 41.169258]"
19,20000089,1372639181,"[[-8.643807, 41.168979], [-8.642529, 41.170113...",0,0,1,1,"[-8.647911, 41.1786]"
20,20000423,1372638161,"[[-8.609706, 41.151303], [-8.609562, 41.151474...",0,0,1,1,"[-8.621064, 41.16114]"
21,20000657,1372637254,"[[-8.660646, 41.168574], [-8.661087, 41.167926...",1,0,0,1,"[-8.601894, 41.181813]"
22,20000320,1372638502,"[[-8.612955, 41.140377], [-8.612991, 41.140359...",0,0,1,1,"[-8.60247, 41.15592]"
23,20000309,1372639960,"[[-8.60418, 41.160969], [-8.603874, 41.1615], ...",0,1,0,1,"[-8.579763, 41.167899]"
24,20000596,1372637658,"[[-8.665686, 41.170626], [-8.665677, 41.170653...",1,0,0,1,"[-8.654337, 41.187816]"
25,20000233,1372639092,"[[-8.632737, 41.168295], [-8.6328, 41.16825], ...",0,0,1,1,"[-8.6328, 41.168232]"
26,20000161,1372639535,"[[-8.648226, 41.148333], [-8.648514, 41.148297...",1,0,0,1,"[-8.58825, 41.097357]"
27,20000596,1372640499,"[[-8.638227, 41.159592], [-8.637543, 41.15925]...",0,0,1,1,"[-8.611596, 41.150439]"
28,20000178,1372639635,"[[-8.613243, 41.154444], [-8.612811, 41.153733...",0,1,0,1,"[-8.613315, 41.166891]"
29,20000235,1372640555,"[[-8.611065, 41.149431], [-8.611209, 41.149368...",0,0,1,1,"[-8.619993, 41.146839]"
...,...,...,...,...,...,...,...,...
99970,20000017,1374432274,"[[-8.566857, 41.163363], [-8.566866, 41.163372...",1,0,0,1,"[-8.598231, 41.150052]"
99971,20000409,1374432386,"[[-8.654931, 41.155686], [-8.655624, 41.155443...",1,0,0,1,"[-8.614026, 41.146191]"
99972,20000482,1374434095,"[[-8.639838, 41.159745], [-8.640459, 41.159772...",0,1,0,1,"[-8.630505, 41.157081]"
99973,20000161,1374381091,"[[-8.628885, 41.161041], [-8.628786, 41.160969...",0,0,1,1,"[-8.589753, 41.176287]"
99974,20000640,1374433135,"[[-8.672607, 41.149008], [-8.670933, 41.148882...",0,0,1,1,"[-8.613063, 41.140467]"
99975,20000520,1374431233,"[[-8.585685, 41.148576], [-8.585694, 41.148675...",0,1,0,1,"[-8.658954, 41.148351]"
99976,20000697,1374428577,"[[-8.678367, 41.15304], [-8.679078, 41.15385],...",1,0,0,1,"[-8.688501, 41.209452]"
99977,20000410,1374432928,"[[-8.640729, 41.160033], [-8.640828, 41.16006]...",1,0,0,1,"[-8.620146, 41.129568]"
99978,20000007,1374425122,"[[-8.630478, 41.154804], [-8.630505, 41.15475]...",0,1,0,1,"[-8.605953, 41.124186]"
99979,20000574,1374433432,"[[-8.647785, 41.150799], [-8.647704, 41.150754...",1,0,0,1,"[-8.677035, 41.151798]"
99980,20000047,1374433957,"[[-8.613117, 41.14341], [-8.613054, 41.143446]...",0,0,1,1,"[-8.604135, 41.149503]"
99981,20000623,1374433518,"[[-8.619966, 41.146812], [-8.619993, 41.146812...",1,0,0,1,"[-8.60337, 41.166522]"
99982,20000345,1374434466,"[[-8.587962, 41.147469], [-8.587827, 41.147784...",1,0,0,1,"[-8.607915, 41.147199]"
99983,20000557,1374434094,"[[-8.612586, 41.145921], [-8.612199, 41.146038...",0,1,0,1,"[-8.639316, 41.1597]"
99984,20000352,1374432882,"[[-8.654265, 41.180526], [-8.653977, 41.179914...",0,0,1,1,"[-8.63838, 41.187789]"
99985,20000686,1374433783,"[[-8.608698, 41.147874], [-8.608554, 41.14773]...",0,1,0,1,"[-8.690859, 41.180481]"
99986,20000341,1374434268,"[[-8.607303, 41.14566], [-8.607069, 41.145885]...",1,0,0,1,"[-8.584047, 41.163192]"
99987,20000419,1374431063,"[[-8.610822, 41.145615], [-8.610849, 41.14566]...",0,0,1,1,"[-8.624997, 41.148522]"
99988,20000658,1374432016,"[[-8.610903, 41.145579], [-8.610948, 41.14566]...",0,1,0,1,"[-8.640684, 41.161032]"
99989,20000146,1374434617,"[[-8.615538, 41.14071], [-8.61552, 41.140692],...",0,1,0,1,"[-8.65035, 41.151042]"
99990,20000250,1374433008,"[[-8.60652, 41.144589], [-8.60697, 41.144742],...",0,1,0,1,"[-8.559405, 41.144769]"
99991,20000023,1374432749,"[[-8.688888, 41.174406], [-8.689023, 41.175819...",1,0,0,1,"[-8.645409, 41.164353]"
99992,20000618,1374434381,"[[-8.574732, 41.14269], [-8.574723, 41.142663]...",1,0,0,1,"[-8.60967, 41.140944]"
99993,20000384,1374431340,"[[-8.607105, 41.150277], [-8.607105, 41.150268...",0,1,0,1,"[-8.621397, 41.160483]"
99994,20000271,1374431335,"[[-8.613252, 41.147901], [-8.61309, 41.148306]...",1,0,0,1,"[-8.670051, 41.236965]"
99995,20000398,1374433338,"[[-8.649297, 41.154309], [-8.650044, 41.154228...",0,1,0,1,"[-8.635509, 40.975947]"
99996,20000506,1374433379,"[[-8.6139, 41.141133], [-8.613891, 41.141115],...",0,1,0,1,"[-8.674533, 41.154174]"
99997,20000435,1374433756,"[[-8.606475, 41.144508], [-8.60652, 41.144517]...",0,1,0,1,"[-8.6778, 41.157666]"
99998,20000074,1374434789,"[[-8.604945, 41.149692], [-8.605368, 41.149773...",1,0,0,1,"[-8.630406, 41.157945]"
99999,20000174,1374432807,"[[-8.606799, 41.150997], [-8.606808, 41.15097]...",0,1,0,1,"[-8.6004, 41.169636]"

In [11]:
chunk.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9960 entries, 0 to 9999
Data columns (total 8 columns):
TAXI_ID        9960 non-null int64
TIMESTAMP      9960 non-null int64
POLYLINE       9960 non-null object
CALL_TYPE_A    9960 non-null float64
CALL_TYPE_B    9960 non-null float64
CALL_TYPE_C    9960 non-null float64
DAY_TYPE_A     9960 non-null float64
Y              9960 non-null object
dtypes: float64(4), int64(2), object(2)
memory usage: 700.3+ KB

In [40]:
def get_lons_lats(df):
    lons = df.POLYLINE.apply(lambda x: x[:,0].ravel())
    lats = df.POLYLINE.apply(lambda x: x[:,1].ravel())
    ylon = df.Y.apply(lambda x: x[0])
    ylat = df.Y.apply(lambda x: x[1])
    df.drop('POLYLINE', axis='columns', inplace=True)
    df.drop('Y', axis='columns', inplace=True)
    df['LONS'] = lons
    df['LATS'] = lats
    df['Y_LON'] = ylon
    df['Y_LAT'] = ylat
    return df

In [41]:
chunk = get_lons_lats(chunk)

In [42]:
chunk

,TAXI_ID,TIMESTAMP,CALL_TYPE_A,CALL_TYPE_B,CALL_TYPE_C,DAY_TYPE_A,LONS,LATS,Y_LON,Y_LAT
0,20000589,1372636858,0,0,1,1,"[-8.618643, -8.618499, -8.620326, -8.622153, -...","[41.141412, 41.141376, 41.14251, 41.143815, 41...",-8.630838,41.154489
1,20000596,1372637303,0,1,0,1,"[-8.639847, -8.640351, -8.642196, -8.644455, -...","[41.159826, 41.159871, 41.160114, 41.160492, 4...",-8.665740,41.170671
2,20000320,1372636951,0,0,1,1,"[-8.612964, -8.613378, -8.614215, -8.614773, -...","[41.140359, 41.14035, 41.140278, 41.140368, 41...",-8.615970,41.140530
3,20000520,1372636854,0,0,1,1,"[-8.574678, -8.574705, -8.574696, -8.57466, -8...","[41.151951, 41.151942, 41.151933, 41.15196, 41...",-8.607996,41.142915
4,20000337,1372637091,0,0,1,1,"[-8.645994, -8.645949, -8.646048, -8.646804, -...","[41.18049, 41.180517, 41.180049, 41.178888, 41...",-8.687268,41.178087
5,20000231,1372636965,0,0,1,1,"[-8.615502, -8.614854, -8.613351, -8.609976, -...","[41.140674, 41.140926, 41.14152, 41.140854, 41...",-8.578224,41.160717
6,20000456,1372637210,0,0,1,1,"[-8.57952, -8.580942, -8.582706, -8.584092, -8...","[41.145948, 41.145039, 41.145021, 41.146164, 4...",-8.603973,41.142816
7,20000011,1372637299,0,0,1,1,"[-8.617563, -8.617527, -8.616978, -8.615754, -...","[41.146182, 41.145849, 41.144832, 41.145426, 4...",-8.624700,41.161554
8,20000403,1372637274,0,0,1,1,"[-8.611794, -8.611785, -8.612001, -8.612622, -...","[41.140557, 41.140575, 41.140566, 41.140503, 4...",-8.589402,41.163309
9,20000320,1372637905,0,0,1,1,"[-8.615907, -8.614449, -8.613522, -8.609904, -...","[41.140557, 41.141088, 41.14143, 41.140827, 41...",-8.604594,41.134158
10,20000233,1372636875,0,0,1,1,"[-8.619894, -8.620164, -8.62065, -8.62092, -8....","[41.148009, 41.14773, 41.148513, 41.150313, 41...",-8.609490,41.157351
11,20000520,1372637984,0,0,1,1,"[-8.56242, -8.562429, -8.562348, -8.564571, -8...","[41.168403, 41.168358, 41.167953, 41.167125, 4...",-8.623017,41.164218
12,20000571,1372637343,1,0,0,1,"[-8.618868, -8.6175, -8.615079, -8.613468, -8....","[41.155101, 41.154912, 41.154525, 41.154228, 4...",-8.575065,41.162265
13,20000233,1372638595,0,0,1,1,"[-8.608716, -8.607627, -8.606502, -8.606493, -...","[41.153499, 41.153481, 41.153472, 41.153472, 4...",-8.632737,41.168295
14,20000231,1372638151,0,0,1,1,"[-8.612208, -8.612235, -8.614035, -8.614809, -...","[41.14053, 41.140521, 41.140323, 41.14035, 41....",-8.606772,41.158260
15,20000497,1372637610,0,1,0,1,"[-8.585145, -8.584146, -8.583147, -8.627931, -...","[41.164857, 41.164704, 41.164758, 41.157954, 4...",-8.628147,41.157522
16,20000403,1372638481,0,1,0,1,"[-8.584263, -8.584695, -8.585595, -8.585487, -...","[41.163156, 41.163003, 41.162652, 41.161437, 4...",-8.641566,41.142672
17,20000570,1372639135,1,0,0,1,"[-8.666757, -8.666784, -8.666649, -8.666325, -...","[41.174055, 41.174064, 41.174073, 41.174847, 4...",-8.662554,41.181714
18,20000005,1372637482,0,0,1,1,"[-8.599239, -8.598681, -8.597943, -8.596962, -...","[41.149188, 41.149296, 41.150583, 41.152266, 4...",-8.584326,41.169258
19,20000089,1372639181,0,0,1,1,"[-8.643807, -8.642529, -8.642133, -8.64324, -8...","[41.168979, 41.170113, 41.171202, 41.172723, 4...",-8.647911,41.178600
20,20000423,1372638161,0,0,1,1,"[-8.609706, -8.609562, -8.610021, -8.609769, -...","[41.151303, 41.151474, 41.152509, 41.153409, 4...",-8.621064,41.161140
21,20000657,1372637254,1,0,0,1,"[-8.660646, -8.661087, -8.661231, -8.660637, -...","[41.168574, 41.167926, 41.166576, 41.166396, 4...",-8.601894,41.181813
22,20000320,1372638502,0,0,1,1,"[-8.612955, -8.612991, -8.61309, -8.613297, -8...","[41.140377, 41.140359, 41.140368, 41.14035, 41...",-8.602470,41.155920
23,20000309,1372639960,0,1,0,1,"[-8.60418, -8.603874, -8.60391, -8.603919, -8....","[41.160969, 41.1615, 41.161527, 41.162022, 41....",-8.579763,41.167899
24,20000596,1372637658,1,0,0,1,"[-8.665686, -8.665677, -8.664786, -8.663238, -...","[41.170626, 41.170653, 41.171319, 41.172453, 4...",-8.654337,41.187816
25,20000233,1372639092,0,0,1,1,"[-8.632737, -8.6328, -8.632845, -8.632836, -8....","[41.168295, 41.16825, 41.168205, 41.168178, 41...",-8.632800,41.168232
26,20000161,1372639535,1,0,0,1,"[-8.648226, -8.648514, -8.648784, -8.650827, -...","[41.148333, 41.148297, 41.148153, 41.148045, 4...",-8.588250,41.097357
27,20000596,1372640499,0,0,1,1,"[-8.638227, -8.637543, -8.635158, -8.633196, -...","[41.159592, 41.15925, 41.158881, 41.158926, 41...",-8.611596,41.150439
28,20000178,1372639635,0,1,0,1,"[-8.613243, -8.612811, -8.611965, -8.61192, -8...","[41.154444, 41.153733, 41.154642, 41.156667, 4...",-8.613315,41.166891
29,20000235,1372640555,0,0,1,1,"[-8.611065, -8.611209, -8.611236, -8.611794, -...","[41.149431, 41.149368, 41.148243, 41.147901, 4...",-8.619993,41.146839
...,...,...,...,...,...,...,...,...,...,...
99970,20000017,1374432274,1,0,0,1,"[-8.566857, -8.566866, -8.566803, -8.568018, -...","[41.163363, 41.163372, 41.162454, 41.162004, 4...",-8.598231,41.150052
99971,20000409,1374432386,1,0,0,1,"[-8.654931, -8.655624, -8.655462, -8.654886, -...","[41.155686, 41.155443, 41.153859, 41.152347, 4...",-8.614026,41.146191
99972,20000482,1374434095,0,1,0,1,"[-8.639838, -8.640459, -8.640468, -8.640675, -...","[41.159745, 41.159772, 41.159808, 41.159583, 4...",-8.630505,41.157081
99973,20000161,1374381091,0,0,1,1,"[-8.628885, -8.628786, -8.628543, -8.628021, -...","[41.161041, 41.160969, 41.160906, 41.161617, 4...",-8.589753,41.176287
99974,20000640,1374433135,0,0,1,1,"[-8.672607, -8.670933, -8.669439, -8.667432, -...","[41.149008, 41.148882, 41.148288, 41.147505, 4...",-8.613063,41.140467
99975,20000520,1374431233,0,1,0,1,"[-8.585685, -8.585694, -8.585694, -8.585694, -...","[41.148576, 41.148675, 41.148684, 41.148954, 4...",-8.658954,41.148351
99976,20000697,1374428577,1,0,0,1,"[-8.678367, -8.679078, -8.680248, -8.68077, -8...","[41.15304, 41.15385, 41.155263, 41.155866, 41....",-8.688501,41.209452
99977,20000410,1374432928,1,0,0,1,"[-8.640729, -8.640828, -8.6409, -8.640927, -8....","[41.160033, 41.16006, 41.160069, 41.16006, 41....",-8.620146,41.129568
99978,20000007,1374425122,0,1,0,1,"[-8.630478, -8.630505, -8.630613, -8.630694, -...","[41.154804, 41.15475, 41.153706, 41.152653, 41...",-8.605953,41.124186
99979,20000574,1374433432,1,0,0,1,"[-8.647785, -8.647704, -8.647812, -8.648892, -...","[41.150799, 41.150754, 41.150763, 41.150691, 4...",-8.677035,41.151798
99980,20000047,1374433957,0,0,1,1,"[-8.613117, -8.613054, -8.612343, -8.611317, -...","[41.14341, 41.143446, 41.143869, 41.144724, 41...",-8.604135,41.149503
99981,20000623,1374433518,1,0,0,1,"[-8.619966, -8.619993, -8.62002, -8.619966, -8...","[41.146812, 41.146812, 41.146812, 41.146695, 4...",-8.603370,41.166522
99982,20000345,1374434466,1,0,0,1,"[-8.587962, -8.587827, -8.587521, -8.587161, -...","[41.147469, 41.147784, 41.148315, 41.148855, 4...",-8.607915,41.147199
99983,20000557,1374434094,0,1,0,1,"[-8.612586, -8.612199, -8.612091, -8.61219, -8...","[41.145921, 41.146038, 41.146839, 41.147829, 4...",-8.639316,41.159700
99984,20000352,1374432882,0,0,1,1,"[-8.654265, -8.653977, -8.652888, -8.652609, -...","[41.180526, 41.179914, 41.180031, 41.179302, 4...",-8.638380,41.187789
99985,20000686,1374433783,0,1,0,1,"[-8.608698, -8.608554, -8.60859, -8.608662, -8...","[41.147874, 41.14773, 41.147685, 41.147622, 41...",-8.690859,41.180481
99986,20000341,1374434268,1,0,0,1,"[-8.607303, -8.607069, -8.606853, -8.606943, -...","[41.14566, 41.145885, 41.146695, 41.146758, 41...",-8.584047,41.163192
99987,20000419,1374431063,0,0,1,1,"[-8.610822, -8.610849, -8.610777, -8.610462, -...","[41.145615, 41.14566, 41.145723, 41.146119, 41...",-8.624997,41.148522
99988,20000658,1374432016,0,1,0,1,"[-8.610903, -8.610948, -8.610957, -8.610966, -...","[41.145579, 41.14566, 41.14566, 41.145696, 41....",-8.640684,41.161032
99989,20000146,1374434617,0,1,0,1,"[-8.615538, -8.61552, -8.615754, -8.61669, -8....","[41.14071, 41.140692, 41.140674, 41.140584, 41...",-8.650350,41.151042
99990,20000250,1374433008,0,1,0,1,"[-8.60652, -8.60697, -8.607492, -8.607951, -8....","[41.144589, 41.144742, 41.143995, 41.143356, 4...",-8.559405,41.144769
99991,20000023,1374432749,1,0,0,1,"[-8.688888, -8.689023, -8.689167, -8.689329, -...","[41.174406, 41.175819, 41.177196, 41.178582, 4...",-8.645409,41.164353
99992,20000618,1374434381,1,0,0,1,"[-8.574732, -8.574723, -8.574894, -8.575857, -...","[41.14269, 41.142663, 41.142771, 41.143284, 41...",-8.609670,41.140944
99993,20000384,1374431340,0,1,0,1,"[-8.607105, -8.607105, -8.607159, -8.608122, -...","[41.150277, 41.150268, 41.150178, 41.150205, 4...",-8.621397,41.160483
99994,20000271,1374431335,1,0,0,1,"[-8.613252, -8.61309, -8.614287, -8.614665, -8...","[41.147901, 41.148306, 41.148423, 41.147595, 4...",-8.670051,41.236965
99995,20000398,1374433338,0,1,0,1,"[-8.649297, -8.650044, -8.65017, -8.649351, -8...","[41.154309, 41.154228, 41.154012, 41.154048, 4...",-8.635509,40.975947
99996,20000506,1374433379,0,1,0,1,"[-8.6139, -8.613891, -8.614359, -8.615457, -8....","[41.141133, 41.141115, 41.140953, 41.140611, 4...",-8.674533,41.154174
99997,20000435,1374433756,0,1,0,1,"[-8.606475, -8.60652, -8.606664, -8.607042, -8...","[41.144508, 41.144517, 41.144607, 41.144823, 4...",-8.677800,41.157666
99998,20000074,1374434789,1,0,0,1,"[-8.604945, -8.605368, -8.605647, -8.605674, -...","[41.149692, 41.149773, 41.149755, 41.149701, 4...",-8.630406,41.157945
99999,20000174,1374432807,0,1,0,1,"[-8.606799, -8.606808, -8.606475, -8.605863, -...","[41.150997, 41.15097, 41.151213, 41.152284, 41...",-8.600400,41.169636

In [43]:
def trunc_chunk(cell, min_feats=20, trunc_pct=50):
    l = len(cell)
    z = np.zeros((min_feats))
    if l <= min_feats:
        z[min_feats-l:] = cell[:]
        z[:min_feats-l] = cell[0]
    elif l <= 2*min_feats:
        z[:] = cell[:min_feats]
    else:
        tl = (l*trunc_pct)//100
        z[:] = cell[tl-min_feats:tl]
    return z

In [52]:
def trunc_for_pred(cell, min_feats=20):
    # Different than `trunc_chunk` since you really want the more recent 20 points, not a truncated polyline
    l = len(cell)
    z = np.zeros((min_feats))
    if l <= min_feats:
        z[min_feats-l:] = cell[:]
        z[:min_feats-l] = cell[0]
    else:
        z[:] = cell[-min_feats:]
    return z

In [44]:
chunk.LONS = chunk.LONS.apply(trunc_chunk)

In [45]:
chunk.LATS = chunk.LATS.apply(trunc_chunk)

In [46]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.cross_validation import KFold, train_test_split
from sklearn.metrics import mean_squared_error

def series_to_feats(df, label):
    s = df[label]
    s = np.vstack([ss for ss in s.as_matrix()])
    new_df = {'{}_{}'.format(label,k):v for k,v in zip(range(1,21),[s[:,i] for i in range(s.shape[1])])}
    new_df = pd.DataFrame(new_df, index=df.index)
    retdf = pd.concat([df, new_df], axis=1)
    retdf.drop(label, axis='columns', inplace=True)
    return retdf

In [47]:
def kaggle_haversine(coord1, coord2, r = 6371.0):
    lat1, lon1 = coord1
    lat2, lon2 = coord2
    lat = abs(lat1-lat2)*np.pi/180
    lon = abs(lon1-lon2)*np.pi/180
    lat1 = lat1*np.pi/180
    lat2 = lat2*np.pi/180
    a = np.sin(lat/2)*np.sin(lat/2)+np.cos(lat1)*np.cos(lat2)*np.sin(lon/2)*np.sin(lon/2)
    d = 2*np.arctan2(np.sqrt(a),np.sqrt(1-a))
    d = r*d
    return(d)

In [48]:
Y_lons = chunk.Y_LON
Y_lats = chunk.Y_LAT
lat_dat = chunk.drop(['TAXI_ID', 'LONS', 'Y_LON'], axis = 'columns')
lon_dat = chunk.drop(['TAXI_ID', 'LATS', 'Y_LAT'], axis = 'columns')
lat_dat = series_to_feats(lat_dat, 'LATS')
lon_dat = series_to_feats(lon_dat, 'LONS')

In [49]:
lat_dat = lat_dat.drop('Y_LAT', axis='columns')
lon_dat = lon_dat.drop('Y_LON', axis='columns')

In [50]:
lon_dat_train, lon_dat_test, lon_Y_train, lon_Y_test = train_test_split(lon_dat, Y_lons, test_size=0.2, random_state=1)
lat_dat_train, lat_dat_test, lat_Y_train, lat_Y_test = train_test_split(lat_dat, Y_lats, test_size=0.2, random_state=1)

In [51]:
lon_reg = RandomForestRegressor(5000, n_jobs=-1, max_depth=20, random_state=1)
lon_reg.fit(lon_dat_train, lon_Y_train)
lon_preds = lon_reg.predict(lon_dat_test)
mse = mean_squared_error(lon_Y_test, lon_preds)
print 'Longitude MSE: {}'.format(mse)

lat_reg = RandomForestRegressor(5000, n_jobs=-1, max_depth=20, random_state=1)
lat_reg.fit(lat_dat_train, lat_Y_train)
lat_preds = lat_reg.predict(lat_dat_test)
mse = mean_squared_error(lat_Y_test, lat_preds)
print 'Latitude MSE: {}'.format(mse)

hdists = []
true_coords = zip(lat_Y_test, lon_Y_test)
pred_coords = zip(lat_preds, lon_preds)
for c1,c2 in zip(true_coords, pred_coords):
    dist = kaggle_haversine(c1,c2)
    hdists.append(dist)
print 'Mean haversine distance: {:.3f}'.format(np.mean(hdists))

Longitude MSE: 0.000461208898534
Latitude MSE: 0.000391877935462
Mean haversine distance: 1.517

In [53]:
import cPickle as cp

In [57]:
with open('/Users/Bronco/Classes/General_assembly/DAT_SF_13_homework/Final_project/kaggle/taxi_trajectory_prediction/lon_reg_20150519.pk', 'wb') as p1:
    cp.dump(lon_reg, p1, protocol=-1)
with open('/Users/Bronco/Classes/General_assembly/DAT_SF_13_homework/Final_project/kaggle/taxi_trajectory_prediction/lat_reg_20150519.pk', 'wb') as p2:
    cp.dump(lat_reg, p2, protocol=-1)

In [55]:
def kaggle_predict(lon_reg, lat_reg, test_data_path):
    '''Predict destination of the test set based on a pair of 
    trained regressors from sklearn implenting a predict method'''
    td = pd.read_csv(test_data_path)
    td.POLYLINE = td.POLYLINE.apply(qc)
    td.dropna(axis='rows', subset=['POLYLINE'], inplace=True)
    trip_ids = td.TRIP_ID.values
    td.drop(['TRIP_ID', 'MISSING_DATA', 'ORIGIN_CALL','ORIGIN_STAND'], axis = 'columns', inplace=True)
    td = pd.get_dummies(td, columns=['CALL_TYPE', 'DAY_TYPE'])
    td['Y'] = td.POLYLINE.apply(lambda x: x[-1])
    td = get_lons_lats(td)
    td.LONS = td.LONS.apply(trunc_for_pred)
    td.LATS = td.LATS.apply(trunc_for_pred)
    Y_lons = td.Y_LON
    Y_lats = td.Y_LAT
    lat_dat = td.drop(['TAXI_ID', 'LONS', 'Y_LON'], axis = 'columns')
    lon_dat = td.drop(['TAXI_ID', 'LATS', 'Y_LAT'], axis = 'columns')
    lat_dat = series_to_feats(lat_dat, 'LATS')
    lon_dat = series_to_feats(lon_dat, 'LONS')
    lat_dat = lat_dat.drop('Y_LAT', axis='columns')
    lon_dat = lon_dat.drop('Y_LON', axis='columns')
    lon_preds = lon_reg.predict(lon_dat)
    lat_preds = lat_reg.predict(lat_dat)
    path = '/Users/Bronco/Classes/General_assembly/DAT_SF_13_homework/Final_project/kaggle/taxi_trajectory_prediction/'
    with open(path+'submission.csv', 'w') as sub:
        sub.write('"TRIP_ID","LATITUDE","LONGITUDE"\n')
        for c in zip(trip_ids,lat_preds,lon_preds):
            write = '"{}",{:.6f},{:.6f}\n'.format(c[0],c[1],c[2])
            sub.write(write)

In [56]:
path = '/Users/Bronco/Classes/General_assembly/DAT_SF_13_homework/Final_project/kaggle/taxi_trajectory_prediction/test.csv'
kaggle_predict(lon_reg, lat_reg, path)

##Kaggle submission

The submitted dataset scored 3.17 in the kaggle challenge. Training a regressor on the imbalanced dataset (most trajectories end downtown) results in poor performance when it comes to predicting more distant destinations. The testing dataset presumably is more focused on non-downtown performance. Creating a version of the dataset that is less focused on downtown locations will hopefully increase generalization to novel trajectories.